pipeline:
  name: Build go-pipeline-sample
  identifier: Build_abdulmoizz44_go_pipeline_sample_1761464861800
  projectIdentifier: abdulmoiz
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: abdulmoizz44/go-pipeline-sample
        build: <+input>
